### ISSUE TITLE
分布式部署

### ISSUE THREAD

**Issue by ghost** [walkor/workerman-chat#11]
您好，在进行分布式部署时，并不能发现config文件夹，请问怎么破？

**Comment by walkor** [comment]
分布式部署并没有涉及到config文件夹的地方。
http://www.workerman.net/gatewaydoc/gateway-worker-development/gateway-worker-separation.html

**Comment by ghost** [comment]
好的，我看的文档是workerman3的，可能有些不一样，谢谢你
