### ISSUE TITLE
Can I run chat on https server?

### ISSUE THREAD

**Issue by MaksimDzhangirov** [walkor/workerman-chat#12]
I changed this part in index.html: 
`ws = new WebSocket("wss://"+document.domain+":7272");`
and enable ssl in start_gateway.php
```
$context = array(
    'ssl' => array(
        'local_cert' => __DIR__ . '/path',
        'local_pk'   => __DIR__ . '/path'        
    )
);

// gateway process
$gateway = new Gateway("Websocket://0.0.0.0:7272", $context);
$gateway->transport = 'ssl';
```

Get following error:
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca in /home/orgjvpwd/public_html/user_account/video-server/vendor/workerman/workerman/Connection/TcpConnection.php on line 391

SSL Handshake fail.

**Comment by walkor** [comment]
Please upgrade workerman to the latest version.
Try to add ```'verify_peer'  => false```  to $context like this.
```php
$context = array(
    'ssl' => array(
        'local_cert'     => __DIR__ . '/path',
        'local_pk'       => __DIR__ . '/path',
        'verify_peer'  => false,   
    )
);
```

The``` Buffer``` information is displayed when an error occurs like this.
```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number in /home/www/workerman-chat/vendor/workerman/workerman/Connection/TcpConnection.php on line 392

SSL Handshake fail. 
Buffer:20485454502f312e310d0a486f73743a206c6179636861742e776f726b65726d616e2e6e...
```
Please show the ```Buffer``` information.

**Comment by MaksimDzhangirov** [comment]
Adding 
`'verify_peer'  => false, `
didn't help.

My Workerman version:
----------------------- WORKERMAN -----------------------------
Workerman version:3.4.2          PHP version:7.1.5
------------------------ WORKERS -------------------------------
        worker              listen                    processes status
      ChatBusinessWorker  none                       1         [OK]
      ChatGateway         websocket://0.0.0.0:7272   1         [OK]
      Register            text://0.0.0.0:1236        1         [OK]
      WebServer           http://0.0.0.0:55151       2         [OK]
----------------------------------------------------------------

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca in /home/orgjvpwd/public_html/user_account/video-server/test2/vendor/workerman/workerman/Connection/TcpConnection.php on line 391

SSL Handshake fail.
Buffer:
client:217.77.212.188:29684 gateway:127.0.0.1:7272  client_id:7f00000108fc00000001 onClose:''

**Comment by walkor** [comment]
Looks like the certificate is invalid.

**Comment by MaksimDzhangirov** [comment]
What program you use to generate certificate? I use openssl and script make-certs.sh from this page http://stackoverflow.com/questions/19665863/how-do-i-use-a-self-signed-certificate-for-a-https-node-js-server.

**Comment by walkor** [comment]
I purchased the certificate from aliyun.com.

**Comment by MaksimDzhangirov** [comment]
Thanks. Problem was resolved.
