### ISSUE TITLE
workerman-chat not run

### ISSUE THREAD

**Issue by arashilan** [walkor/workerman-chat#13]
[root@iZbp126k55rdoydke33zdtZ workerman-chat]# php start.php kill
Workerman[start.php] kill 
Workerman[start.php] not run
[root@iZbp126k55rdoydke33zdtZ workerman-chat]# php start.php kill
Workerman[start.php] kill 
Workerman[start.php] not run
[root@iZbp126k55rdoydke33zdtZ workerman-chat]# php start.php start -d
Workerman[start.php] start in DAEMON mode
[root@iZbp126k55rdoydke33zdtZ workerman-chat]# php start.php status
Workerman[start.php] status 
Workerman[start.php] not run
=================================================================
excuse me, why?

**Comment by walkor** [comment]
Workerman not run.
