### ISSUE TITLE
如果客户端发送二进制消息应该如何接受？

### ISSUE THREAD

**Issue by xeoshow** [walkor/workerman-chat#26]
您好，

我现在有个c++写的客户端，需要把一个文件发送到服务器端，客户端是按sendBinaryMessage发给服务器端的，需要怎么在workerman-chat的服务器端接受呢？

谢谢！

**Comment by walkor** [comment]
文件用http upload方式发给apache/php-fpm等 webserver 就行了，用不着发给workerman

**Comment by xeoshow** [comment]
收到，谢谢哈
