### ISSUE TITLE
在线状态直接关闭计算机没有调用onClose回调方法

### ISSUE THREAD

**Issue by suunnn** [walkor/workerman-chat#28]
在线状态时直接关闭计算机没有调用onClose回调方法

**Comment by walkor** [comment]
关闭计算机是指关闭服务器？

**Comment by suunnn** [comment]
@walkor 不是，是客户端直接关闭计算机，谢谢

**Comment by walkor** [comment]
直接关闭计算机时客户端不会有机会给服务端发送fin包，服务端也就无法知道客户端已经下线。
这种情需要用心跳来检测，具体看手册[心跳部分](http://doc2.workerman.net/326139)

**Comment by suunnn** [comment]
@walkor ok 谢谢
