### ISSUE TITLE
一个房间里可否支持子组？

### ISSUE THREAD

**Issue by xeoshow** [walkor/workerman-chat#29]
比如一个房间100人，但是只想发消息给里面的10个人（子组），在workerman-chat里应该如何实现呢？

**Comment by walkor** [comment]
给这10个人放到一个分组就好了

**Comment by xeoshow** [comment]
分组是现成有的吗？还是需要二次开发的意思？谢谢！

**Comment by walkor** [comment]
gateway::joinGroup是用来分组的

**Comment by xeoshow** [comment]
谢谢！
