### ISSUE TITLE
支持离线消息持久化

### ISSUE THREAD

**Issue by sanwv** [walkor/workerman-chat#3]
rt

**Comment by sanwv** [comment]
workerman,gateway,chat三部分的源码都看完了,现在是gateway收发消息转给businessworker,businessworker处理逻辑然后由gateway把消息发给客户端

---

为了更好的分层逻辑和保证消息流转稳定性是否可以添加消息队列,即异步地流转消息:

```
1.gateway充当连接器,维持客户端连接
2.连接器收到的消息统一放到消息队列
3.由转发进程消费队列消息,根据规则把消息分发给相应的连接器,最终把数据发给客户端
```

这样任何一个组件都可以多实例运行,平滑重启,任意一点异常最坏也就是暂停消息流转

---

刚开始构建im,在可行性上积极探讨,期待建议性意见^_^

**Comment by walkor** [comment]
增加队列可能会带来某些好处，
但是增加了程序的复杂性，加了通讯开销，并且增加了用户的学习成本、部署成本、甚至开发成本。
增加队列要考虑提供队列转发规则接口，相关队列配置、队列容灾、队列扩容方案等等，开发难度也很大

目前gateway businessworker都是可以多实例运行，独立部署的，支持平滑重启，即使businessworker有实例挂掉，也几乎是零影响，感觉没有必要增加队列机制。

如果开发者有能力的并且有需要的话，可以加一层队列。但是官方gatewayWorker本身应该不会增加这一层。
