### ISSUE TITLE
Problem for 100+ online user

### ISSUE THREAD

**Issue by sm2017** [walkor/workerman-chat#8]
Hello
I install and run https://github.com/walkor/workerman-chat on my server with 40GB RAM , CENTOS , 8 CORE CPU 1.8 GHz , PHP 7 and Libev installed

After I have only 150 online user , workerman cannot handle messages , sometime a message send after 5 -10 seconds , sometime lost

1- Where is problem? How can I handle at least 100,000 online user? 150 user for this server is not good 
2- How much user I can handle with workerman? in this server?

**Comment by walkor** [comment]
Please use event extension not Libev.

Please increase maximum file open  limit (ulimit)  65535 for example.

Yes, workerman can handle more then 100,000 connections for your server.

**Comment by sm2017** [comment]
Thanks for your reply
If I want to handle 10 million online user , what must I do? (Each user send 15 message per minutes)
Please let me know
1- Recommended server (OS,CPU,RAM,PHP version)
2- What is best choice? LibEvent - LibEv - Event ?
3- What is best choice for $gateway->count ? for Gateway and BusinessWorker , please compare if I have 8 core CPU and 100 core cloud cpu
4- Best choice for $gateway->pingInterval and $gateway->pingNotResponseLimit , I need accurate online status (2-3 minutes accuracy is enough)
5- What happened If I disable pingInterval  and pingNotResponseLimit , assume online status is not important and a user is idle for 10 hours , We lost connection? how long it take we lost an idle connection usually?
6- Is it good idea to remove Statistic? (StatisticProvider - StatisticWorker , ..)

I know I ask many question , but I need to ask , please reply me in detail

Best Regards and thanks a lot

**Comment by walkor** [comment]
1、php5.6 
2、libevent Recommended
3、$gateway->count=num_cpucore and $gateway->count=num_cpucore*2
4、$gateway->pingInterval=30, $gateway->pingNotResponseLimit=1
5、Some firewall will close connections witch idle for some time(may be 30 seconds). 
6、Statistic is removed for current repo.

You need a distributed deployment workerman-chat to accommodate 10 million connections.
See 
http://www.workerman.net/gatewaydoc/gateway-worker-development/why-distributed.html<br> 
http://www.workerman.net/gatewaydoc/gateway-worker-development/how-distributed.html<br>
http://www.workerman.net/gatewaydoc/gateway-worker-development/gateway-worker-separation.html<br>  
Sorry no english documents<br>

**Comment by sm2017** [comment]
In my test , I have 4 Gateway and 4 BusinessWorker , When only 1 client connect to server and send message , I see only 1 BusinessWorker works , why? even I send 10000 msg/sec?
In my BusinessWorker I place sleep(10) at the end of script (After Gateway::sendToGroup) and when I send 4 message to server It must broadcast message immediately but only 1 BusinessWorker receive message and  broadcasting take 30 sec why? why all BusinessWorker dont works?

**Comment by walkor** [comment]
GatewayWorker has **[router module](http://www.workerman.net/gatewaydoc/gateway-worker-development/router.html)**.  
By default one client bind to one BusinessWorker.  
You can change it by setting `$gateway->router` in start_gateway.php like this.  

``` php
$gateway->router = function($worker_connections, $client_connection, $cmd, $buffer)
{
    return $worker_connections[array_rand($worker_connections)];
};
```

**Why one client bind to one BusinessWorker?** 
 Because events(onConnect/onMessage/onClose) may out of order when multi BusinessWorker receive and deal them.

**Comment by sm2017** [comment]
1 More question
I test workerman chat and for simple echo I send 20,000 message per second and all thing is good, very nice performance , RAM and CPU usage 

But If our BusinessWorker do a work that take time (For example 50ms ) , BusinessWorker block for 50ms and even 1000 request per second is high and workerman cannot reply , For example when in echo I put sleep(1) and echo , workerman cannot hande 100 request per second , Why?
As you know sleep(1) , is just sleep for 1 sec and CPU is idle , I try usleep(150000) to simulate database connection , or use pdo to connect to database in all of these function cpu is idle but BusinessWorker block incoming data
How can I do this? If we have sleep(1) in our Event::onMessage , sleep dont block next request

**Comment by walkor** [comment]
If BusinessWorker has blocking codes like reading mysql, you can increase $business_worker->count.

You can also put blocking codes into other workers by using [AsyncTcpConnection](http://doc3.workerman.net/worker-development/__construct.html)  like [this document(async tasks)](http://doc3.workerman.net/faq/async-task.html). These worker processes(async tasks processes) can be deployed to other servers.

**Comment by sm2017** [comment]
What is difference if we forward to AsyncTcpConnection? assume all message processing need 100 ms to be done , Instead of BusinessWorker blocking codes we have blocking codes in AsyncTcpConnection , right?

**Comment by walkor** [comment]
Instead of BusinessWorker blocking codes we have blocking codes in other workers.

**Comment by sm2017** [comment]
So what is advantage of AsyncTcpConnection?
For simple question , just assume that we get message from client , we want sleep(1) and echo back to client , It is just example and I never want do it

The question is , sleep(1) is idle processing so we can handle other client's messages,[ like nodeJS , JAVA , ...]
How we can do this in PHP?

**Comment by walkor** [comment]
``` php
use Workerman\Worker;
require_once './Workerman/Autoloader.php';
// task worker，使用Text协议
$task_worker = new Worker('Text://0.0.0.0:12345');
$task_worker->count = 100;
$task_worker->name = 'TaskWorker';
$task_worker->onMessage = function($connection, $task_data)
{
     $task_data = json_decode($task_data, true);
     sleep(1); // send mail
     $connection->send(json_encode('task complete'));
};
Worker::runAll();
```

``` php
public static function onMessage($client_id, $message)
{
    $task_connection = new AsyncTcpConnection('Text://ip:12345');
    $task_data = array(
        'function' => 'send_mail',
        'args'       => array('from'=>'xxx', 'to'=>'xxx', 'contents'=>'xxx'),
    );
    $task_connection->send(json_encode($task_data));
    $task_connection->onMessage = function($task_connection, $task_result)use($client_id)
    {
         var_dump($task_result);
         $task_connection->close();
         Gateway::sendToClient($task_result); // $task_result value is task complete.
    };
    $task_connection->connect();
}
```

BusinessWorker will not be blocked in this example.  Blocking codes will be executed in other processes of servers.

**Comment by sm2017** [comment]
In this code , If we have 8 AsyncTcpConnection worker , we only can call $task_connection->send , 8 time per seconds right? [I know we have buffer for $task_worker and we can call $task_connection->send many more time per seconds but If we want reply to client by  $task_connection->onMessage and Gateway::sendToClient($task_result); and if we have 100 request per seconds 100th client must wait for minutes for reply , right?]

**Comment by walkor** [comment]
Yes. But you can create more than 8 workers.

**Comment by sm2017** [comment]
How many thread can I have? on my server with 40GB RAM , CENTOS , 8 CORE CPU 1.8 GHz

**Comment by walkor** [comment]
16-64.
