### ISSUE TITLE
Local communication protocol

### ISSUE THREAD

**Issue by sm2017** [walkor/workerman-chat#9]
How can I use AF_UNIX (unix://) for gateway and business worker communications?

In case of Distributed Deployment , how can I config gateways that only connect to local business workers?

**Comment by walkor** [comment]
Currently not  support AF_UNIX (unix://) for gateway and business worker communications.

You can use router callback to connect to local business workers like this.

``` php
$gateway = new Gateway("Websocket://0.0.0.0:8585");
$gateway->router = function($worker_connections, $client_connection, $cmd, $buffer)
{
    //var_dump($worker_connections);
    $local_worker_process_count = xx;
    $local_worker_ip = 'xx.xx.xx.xx';
    $local_worker_name = 'xxx';
    return $worker_connections["{$local_worker_ip}:{$local_worker_name}:".rand(0, $local_worker_process_count-1)];
};
```

Here is [docs](http://www.workerman.net/gatewaydoc/gateway-worker-development/router.html) for router.  Sorry, there is no English version of the docs currently.
